version: 2
updates:
  - package-ecosystem: composer
    directory: /server
    schedule:
      interval: weekly
      day: sunday
    reviewers:
      - martin-juul
  - package-ecosystem: yarn
    directory: /client
    schedule:
      interval: weekly
      day: sunday
    reviewers:
      - martin-juul
