version: '2'

services:
  db:
    container_name: scratcher-db
    image: postgres:13-alpine
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - scratcher-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scratcher
      - POSTGRES_USER=scratcher
      - POSTGRES_PASSWORD=secret

networks:
  scratcher-net:

volumes:
  pgdata:
